version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "@lekman"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    # Group all action updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain dependencies for Swift Package Manager
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "@lekman"
    labels:
      - "dependencies"
      - "swift"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
