---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
