name: "Setup Swift Build Environment"
description: "Sets up Swift toolchain and SPM caching for efficient builds"

inputs:
  swift-version:
    description: "Swift version to use"
    required: false
    default: "6.0"
  cache-key-suffix:
    description: "Additional suffix for cache key"
    required: false
    default: "v6-macos15"
  project-path:
    description: "Path to the Swift package directory"
    required: false
    default: "MagSafeGuardLib"

outputs:
  spm-cache-hit:
    description: "Whether SPM cache was hit"
    value: ${{ steps.spm-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Swift
      id: setup-swift-toolchain
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ inputs.swift-version }}

    - name: Get Swift version for cache key
      id: swift-version
      shell: bash
      run: |
        SWIFT_VERSION=$(swift --version | head -n1 | sed 's/.*version \([0-9.]*\).*/\1/')
        echo "version=$SWIFT_VERSION" >> $GITHUB_OUTPUT
        echo "Swift version: $SWIFT_VERSION"

    - name: Create cache directories
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
      run: |
        # Create directories that will be cached to avoid warnings
        mkdir -p "$PROJECT_PATH/.build"
        mkdir -p ~/.swiftpm
        mkdir -p ~/Library/Caches/org.swift.swiftpm

    - name: Cache Swift Package Manager dependencies
      id: spm-cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ${{ inputs.project-path }}/.build
          ~/.swiftpm
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-${{ runner.arch }}-swift${{ steps.swift-version.outputs.version }}-spm-${{ hashFiles(format('{0}/Package.swift', inputs.project-path), format('{0}/Package.resolved', inputs.project-path)) }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-swift${{ steps.swift-version.outputs.version }}-spm-${{ hashFiles(format('{0}/Package.swift', inputs.project-path)) }}-
          ${{ runner.os }}-${{ runner.arch }}-swift${{ steps.swift-version.outputs.version }}-spm-
          ${{ runner.os }}-${{ runner.arch }}-spm-

    - name: Resolve Swift Package Dependencies
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
      run: |
        echo "📦 Resolving Swift package dependencies..."
        cd "$PROJECT_PATH" && swift package resolve
        echo "✅ Dependencies resolved"

    - name: Cache and Install Taskfile
      uses: ./.github/actions/taskfile
      with:
        cache-key-suffix: ${{ inputs.cache-key-suffix }}
