name: 'Setup Swift Build Environment'
description: 'Sets up Swift toolchain, Xcode, and caching for efficient builds'

inputs:
  swift-version:
    description: 'Swift version to use'
    required: false
    default: '5.9'
  xcode-version:
    description: 'Xcode version to use'
    required: false
    default: 'latest-stable'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

outputs:
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Swift
      if: runner.os == 'Linux'
      uses: swift-actions/setup-swift@1c8768daf6498a797dd4cabf37c3a3628406b779 # v2
      with:
        swift-version: ${{ inputs.swift-version }}

    - name: Set up Xcode
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@c51a66b42363123fa82a6cfe02c60af4281dab93 # v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Cache SPM dependencies
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          .build
          ~/.swiftpm
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', '**/Package.resolved') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-spm-${{ hashFiles('Package.swift', '**/Package.resolved') }}
          ${{ runner.os }}-spm-

    - name: Install Taskfile if needed
      shell: bash
      run: |
        if ! command -v task &> /dev/null; then
          echo "Installing Taskfile..."
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install go-task/tap/go-task
          else
            # For Linux runners
            curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin
          fi
        fi
        echo "Taskfile version: $(task --version)"
    
    - name: Create Package.resolved (if using SPM)
      shell: bash
      run: |
        # Only resolve if Package.swift exists
        if [ -f "Package.swift" ] && [ ! -f "Package.resolved" ]; then
          echo "Creating Package.resolved..."
          swift package resolve
        fi

    - name: Validate Swift environment
      shell: bash
      run: |
        echo "Swift version: $(swift --version)"
        echo "Platform: $(uname -a)"
        if [ "$RUNNER_OS" == "macOS" ]; then
          echo "Xcode version: $(xcode-select -p)"
        fi