# GitHub Pages Configuration for MagSafe Guard

# Site settings
title: MagSafe Guard Documentation
description: "Dead-Man's Cord Theft Protection Switch for Your Mac"
baseurl: "" # Leave empty since we're in /docs
url: "https://lekman.github.io/magsafe-buskill" # Full URL

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - .DS_Store
  - "*.swp"
  - "*~"

# Navigation structure (optional - for theme customization)
navigation:
  - title: Home
    url: /
  - title: Architecture
    url: /architecture/
  - title: Security
    url: /security/
  - title: DevOps
    url: /devops/
  - title: Maintainers
    url: /maintainers/