name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    # Only run on files that release-please modifies
    paths:
      - '.github/.release-please-manifest.json'
      - '**/CHANGELOG.md'
      - '**/package.json'
      - '**/package-lock.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  cancel-redundant:
    name: Cancel Redundant Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Cancel redundant workflow runs
        uses: ./.github/actions/cancel-redundant-workflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-please:
    name: "Release Please"
    runs-on: ubuntu-latest
    needs: cancel-redundant
    outputs:
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  auto-approve:
    name: Auto Approve
    needs: release-please
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-please')
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Auto-approve Release PR
        uses: lekman/auto-approve-action@44fbd63e95dc166951bbde068766d178c06bdb94 # v1.0.0
        with:
          allowed-authors: "app/lekman-release-please-bot"
          github-token: ${{ secrets.APPROVE_TOKEN }}
          required-labels: "autorelease: pending"
          label-match-mode: "all"
          path-filters: ".github/.release-please-manifest.json,**/CHANGELOG.md,**/package.json,**/package-lock.json"
          merge-method: "merge"

  merge-on-approval:
    name: Merge
    needs: [release-please, auto-approve]
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.pr }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Enable Auto-merge
        run: |
          gh pr merge ${{ fromJson(needs.release-please.outputs.pr).number }} \
            --auto \
            --merge \
            --delete-branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
