name: Release Please
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    # Only run on files that release-please modifies
    paths:
      - ".github/.release-please-manifest.json"
      - "**/CHANGELOG.md"
      - "**/package.json"
      - "**/package-lock.json"
permissions:
  contents: read
jobs:
  cancel-redundant:
    name: Cancel Redundant Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cancel redundant workflow runs
        uses: ./.github/actions/cancel-redundant-workflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  release-please:
    name: "Release Please"
    runs-on: ubuntu-latest
    needs: cancel-redundant
    outputs:
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json
  auto-approve:
    name: Auto Approve
    needs: release-please
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-please')
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Auto-approve Release PR
        uses: lekman/auto-approve-action@25d5b39fc1a1e8a04ad7473a47f1a9ecd9748fa3 # v1.0.0
        with:
          allowed-authors: "app/lekman-release-please-bot"
          github-token: ${{ secrets.APPROVE_TOKEN }}
          required-labels: "autorelease: pending"
          label-match-mode: "all"
          path-filters: ".github/.release-please-manifest.json,**/CHANGELOG.md,**/package.json,**/package-lock.json"
          merge-method: "merge"
  merge-on-approval:
    name: Merge
    needs: [release-please, auto-approve]
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.pr }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Enable Auto-merge
        run: |
          gh pr merge ${{ fromJson(needs.release-please.outputs.pr).number }} \
            --auto \
            --merge \
            --delete-branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
